___
<a href='https://cafe.naver.com/jmhonglab'><p style="text-align:center;"><img src='https://lh3.googleusercontent.com/lY3ySXooSmwsq5r-mRi7uiypbo0Vez6pmNoQxMFhl9fmZJkRHu5lO2vo7se_0YOzgmDyJif9fi4_z0o3ZFdwd8NVSWG6Ea80uWaf3pOHpR4GHGDV7kaFeuHR3yAjIJjDgfXMxsvw=w2400'  class="center" width="50%" height="50%"/></p></a>
___
<center><em>Content Copyright by HongLab, Inc.</em></center>

# [넘파이(NumPy)](https://numpy.org/)

넘파이(NumPy)는 다차원 배열 계산에서 독보적인 장점을 갖고 있는 과학 계산 패키지입니다. NumPy라는 이름은 Numerical Python에서 나왔습니다. 데이터 과학이나 딥러닝 등 파이썬에서 수치 데이터를 다룰 때 필수적입니다. 아이템 객체들이 메모리 안에서 여기저기 흩어져 있는 리스트와 달리 동일한 자료형의 값들이 나란히 나열되어 있는 배열(array)이기 때문에 속도가 빠르며 다양한 연산들을 한꺼번에 처리할 수 있기 때문에 더 편리합니다. 특히 다차원 배열을 다루는 기능들이 잘 발달해 있습니다.

### 기본적인 개념들




파이썬 리스트로부터 배열을 만들 수 있습니다. 이때 ```ndim```은 배열이 몇 차원(number of dimension)인지를 의미하고 ```shape```은 각 차원(dimension)의 길이(원소의 개수)를 의미합니다.

In [ ]:
import numpy as np  # 보통 np로 줄여서 사용

# 리스트로부터 1차원 배열 생성
a = np.array([1, 2, 3, 4])

print(a.ndim, a.shape, a.size)  # 1 (4,) 4

# 2차원 배열 생성
b = np.array([[1, 2, 3], [4, 5, 6]])
# b = np.array([[1, 2, 3, 4], [5, 6, 7, 8, 9]]) # 경고 발생

print(b.ndim, b.shape, b.size)  # 2 (2, 3) 6

# 3차원 배열 생성
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(c.ndim, c.shape, c.size)  # 3 (2, 2, 3) 12

np.sum(c, axis = 2)

우리가 수학에서 공간 좌표계를 다룰 때는 x-축(axis), y-축 등으로 각 방향에 이름을 붙여서 부르지만 다차원 배열에서는 축(axis)을 지칭할 때 문자 대신에 인덱스를 이용합니다.

In [ ]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])

# axis 이용 사례 sum()
print(np.sum(b))  # 모든 축에 대한 합
print(np.sum(b, axis=0))  # 0번 축을 따라가면서 더하기
print(np.sum(b, axis=1))  # 1번 축을 따라가면서 더하기
# print(np.sum(b, axis=2)) # 2D 배열에는 2번 축이 없기 때문에 오류 발생

# sum()외에 min(), max(), mean() 등도 비슷하게 사용할 수 있습니다.

기능을 사용할 때는 ```np.sum(a)```과 같이 패키지의 함수를 호출하는 방법과 ```a.sum()```과 같이 객체의 메써드를 호출하는 방법 두 가지가 있습니다.

In [ ]:
a = np.array([1, 2, 3, 4])

print(np.sum(a), a.sum())

```dtype```은 각 원소의 자료형입니다. 
- Numpy에서는 하나의 배열은 모두 동일한 자료형이어야 합니다. 예를 들어 리스트에서는 ```[3.14, 1]```같이 ```float```와 ```int```를 하나의 리스트로 묶어두는 것이 가능했지만 배열에서 불가능합니다.  
- 많이 사용되는 ```dtype```에는 ```int32```, ```float64```, ```bool``` 등이 있습니다. ```int32```는 ```int``` 하나에 32비트(4바이트)의 메모리를 사용하는 자료형이라는 의미입니다.  
- 더 많은 메모리를 사용할 수록 더 넓은 범위의 숫자를 표현할 수 있지만 큰 데이터를 다룰 때는 저장 공간과 계산 속도도 고려해야 하기 때문에 최신 기술에 오히려 크기가 작은 자료형(예: ```float16```)을 사용하는 경우도 있습니다.  
- 자료형은 ```astype()``` 메써드로 바꿀 수 있습니다.

In [ ]:
a = np.array([1, 2, 3])

print(a.dtype, a.itemsize) # int32 4

b = np.array([1.0, 2.0, 3.0])

print(b.dtype, b.itemsize) # float64 8

c = a.astype(np.float16)

print(c.dtype, c.itemsize) # float16 2

다양한 방식으로 배열을 만들 수 있습니다.

In [ ]:
a = np.zeros((2, 1)) # shape이 (2, 1)이고 원소가 전부 0.0인 배열
#a = np.array([[0.0], [0.0]])
print(a)

b = np.ones((1, 2)) # shape이 (1, 2)이고 전부 1.0인 배열
print(b)

c = np.full((2, 2), 7) # 모든 값들이 7로 채워진 배열
print(c)

d = np.eye(3) # 대각 원소만 1.0이고 나머지는 0.0인 3x3 2차원 배열
print(d)

e = np.random.random((2, 2)) # [0.0, 1.0) 범위의 float 난수로 채워진 배열
print(e)

f = np.arange(2, 9, 2) # array of range
print(f) # [2, 4, 6, 8]

g = np.linspace(0, 10, num=5) # 간격이 동일한 숫자들
print(g) #[ 0.   2.5  5.   7.5 10. ]

여러 값들에 동일한 계산을 적용할 때 리스트 컴프리헨션을 사용하는 것 보다 편리합니다.

In [ ]:
import numpy as np

my_list = [4, 5, 6]
[x * 2 + 1 for x in my_list]

my_array = np.array([4, 5, 6])
my_array * 2 + 1

배열 단위의 연산도 가능합니다.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 주의: a와 b의 shape가 같아야겠지요.
a * b

배열들을 합칠 수도 있습니다.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.concatenate((a, b)))
# [1 2 3 4 5 6]

print(np.hstack((a, b)))
# [1 2 3 4 5 6]

print(np.vstack((a, b)))
# [[1 2 3]
#  [4 5 6]]

```size```가 동일하다면 ```shape```를 바꿀 수 있습니다. 참고로 ```shape```가 (8,)이면 ```ndim```이 1이고 (8, 1) 또는 (1, 8)이면 ```ndim```이 2입니다.

In [ ]:
a = np.ones((2, 4))
a = a.reshape((4, 2))
a = a.reshape((2, 2, 2))

a = a.reshape((8))
print(a.shape, a.ndim) #(8,) 1

a = a.reshape((1, 8))
print(a.shape, a.ndim) # (1, 8) 2

인덱싱과 슬라이싱을 사용할 수 있습니다.

In [ ]:
# 1D array
a = np.array([1, 2, 3, 4, 5])

print(a[3]) # 4
print(a[::2]) # [1 3 5]
#print(a[100]) # IndexError

In [ ]:
# 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a[0]) # [1 2 3]
print(a[1]) # [4 5 6]
print(a[1, :]) # [4 5 6]
print(a[0, 1]) # 2
print(a[1, 2]) # 6
print(a[1][2]) # 6 a[1]를 만든 후에 다시 [2] 인덱싱


조건식과 배열을 함께 사용하기도 편리합니다.

In [ ]:
a = np.array([1, 2, 3, 4, 5])

print(a[a < 3]) # [1, 2]
print(a < 3) # [ True  True False False False]

b = np.array([[1, 2, 3], [4, 5, 6]])

print(b[b % 2 == 0]) # [2 4 6]
print(b % 2 == 0) # 원래 shape를 유지한 bool의 배열



간단한 선형 대수 연산도 지원합니다.

In [ ]:
a = np.array([[1., 2.], [3., 4.]])
np.linalg.inv(a)

Matplotlib 뿐 아니라 많은 패키지에서 Numpy를 지원합니다.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-np.pi, np.pi, 201)
plt.plot(x, np.sin(x))
plt.show()

**[실습]** 정규 분포 난수의 히스토그램 그려보기

matplotlib에서는 ```hist()```를 이용해서 히스토그램을 그릴 수 있습니다. [numpy.random.normal()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html)을 이용해서 정규 분포 난수의 히스토그램을 그려보세요. 예시에서는 ```loc=0.0, scale=1.0, size=10000```을 사용하였습니다.

In [ ]:
import numpy as np
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt

x = [21,22,23,4,5,6,77,8,9,10,31,32,33,34,35,36,37,18,49,50,100]
num_bins = 5
plt.hist(x, num_bins)
plt.show()

본격적으로 데이터사이언스나 딥러닝을 공부하시기 전에 [기본 튜토리얼](https://numpy.org/doc/stable/user/absolute_beginners.html)을 훑어보시기를 권장합니다.

##### [실습] 몬테 카를로 시뮬레이션으로 원주율 구하기 (Numpy)

**스텝1** 앞에서 풀어봤던 원주율 문제를 Numpy로 다시 풀어봅시다. 대부분의 경우 더 간결해지고 속도도 빨라집니다.

In [ ]:
# 힌트
a = np.array([1, 2, 3, 4, 5])
check = a < 3
c = a[check]
d = a[np.logical_not(check)]
print(c)
print(d)

np.split(a, a<3)

In [ ]:
# Numpy를 사용하는 경우
# 훨씬 빠릅니다.
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)  # 결과 비교를 위해 시드 고정

num_points = 100000


**스텝2** 이번에는 ```scatter()```를 한 번만 호출해보세요. 필요하다면 ```np.count_nonzero()```와 ```np.where()```를 사용할 수 있습니다. 다만, 실행 속도는 더 느릴 수도 있습니다. 코드가 간결하다고 속도가 빠른 것은 아닙니다.

In [ ]:
# Numpy를 사용하는 경우
# 훨씬 빠릅니다.
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)  # 결과 비교를 위해 시드 고정

num_points = 100000
